
const img = (name) => `/uploads/seed/${name}`;

const tiffinHours = [
  { day: "Monday", open: "6:30 AM", close: "9:30 PM" },
  { day: "Tuesday", open: "6:30 AM", close: "9:30 PM" },
  { day: "Wednesday", open: "6:30 AM", close: "9:30 PM" },
  { day: "Thursday", open: "6:30 AM", close: "9:30 PM" },
  { day: "Friday", open: "6:30 AM", close: "9:30 PM" },
  { day: "Saturday", open: "6:30 AM", close: "10:00 PM" },
  { day: "Sunday", open: "6:30 AM", close: "10:00 PM" },
];

const biryaniHours = [
  { day: "Monday", open: "11:00 AM", close: "10:30 PM" },
  { day: "Tuesday", open: "11:00 AM", close: "10:30 PM" },
  { day: "Wednesday", open: "11:00 AM", close: "10:30 PM" },
  { day: "Thursday", open: "11:00 AM", close: "10:30 PM" },
  { day: "Friday", open: "11:00 AM", close: "11:00 PM" },
  { day: "Saturday", open: "11:00 AM", close: "11:00 PM" },
  { day: "Sunday", open: "11:00 AM", close: "10:30 PM" },
];

const fineDiningHours = [
  { day: "Monday", open: "12:00 PM", close: "10:00 PM", isClosed: true },
  { day: "Tuesday", open: "12:00 PM", close: "10:00 PM" },
  { day: "Wednesday", open: "12:00 PM", close: "10:00 PM" },
  { day: "Thursday", open: "12:00 PM", close: "10:00 PM" },
  { day: "Friday", open: "12:00 PM", close: "10:30 PM" },
  { day: "Saturday", open: "12:00 PM", close: "10:30 PM" },
  { day: "Sunday", open: "12:00 PM", close: "10:00 PM" },
];

export const seedUsers = [
  { mockId: "u-1", name: "Kumaran Maran", email: "kumaran.maran@gmail.com", phone: "+91 98765 43210", role: "customer", joinedAt: "2023-08-14" },
  { mockId: "u-2", name: "sanjay", email: "sanjay@gmail.com", phone: "+91 98450 12233", role: "customer", joinedAt: "2023-11-02" },
  { mockId: "u-3", name: "Prem kumar", email: "premkumar@gmail.com", phone: "+91 90031 55678", role: "customer", joinedAt: "2024-01-19" },
  { mockId: "u-4", name: "Rajesh", email: "rajesh@rgmail.com", phone: "+91 97890 66112", role: "owner", joinedAt: "2023-05-30" },
  { mockId: "u-5", name: "Kavitha", email: "kavitha@gmail.com", phone: "+91 96001 99882", role: "owner", joinedAt: "2023-04-11" },
  { mockId: "u-6", name: "prajith", email: "prajith@gmail.com", phone: "+91 94440 66123", role: "admin", joinedAt: "2022-12-01" },
];

export const seedRestaurants = [
  {
    mockId: "r-1",
    ownerMockId: "u-4",
    slug: "rayars-mess",
    name: "Rayar's Mess",
    tagline: "Historic Mylapore icon for authentic South Indian breakfast",
    description:
      "Tucked away in the lanes of Mylapore, Rayar's Mess has been serving fluffy idlis, crisp vadas, and its fiery signature chutney since generations. Expect long queues, no-frills seating, and breakfast exactly the way Chennai has always loved it.",
    coverImage: img("sambar.jpg"),
    gallery: [img("idli-banana-leaf.jpg"), img("vada-plate.jpg"), img("dosa-tray.jpg"), img("restaurant-table.jpg"), img("idli-coffee.jpg"), img("sambar.jpg")],
    cuisines: ["South Indian", "Tiffin", "Filter Coffee"],
    category: "Traditional Mess",
    priceRange: "₹₹",
    rating: 4.7,
    reviewCount: 612,
    location: { address: "18 North Mada Street, Mylapore", city: "Chennai", state: "Tamil Nadu", zip: "600004", lat: 13.0339, lng: 80.2619 },
    facilities: ["Traditional Seating", "Filter Coffee", "Takeout", "Cash Only", "Early Morning Breakfast"],
    openingHours: tiffinHours,
    isOpenNow: true,
    isFeatured: true,
    isTrending: true,
    isTopRated: true,
    seatsAvailable: 8,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: true,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Idli", description: "Steamed rice cakes, served with sambar and coconut chutney", price: 40, category: "Tiffin", image: img("idli-banana-leaf.jpg"), isVeg: true, isPopular: true },
      { name: "Sambar Vada", description: "Crisp lentil fritters soaked in Rayar's signature sambar", price: 45, category: "Tiffin", image: img("vada-plate.jpg"), isVeg: true, isPopular: true },
      { name: "Ghee Roast Dosa", description: "Thin rice crepe roasted in ghee, served with chutney", price: 70, category: "Tiffin", image: img("dosa-tray.jpg"), isVeg: true, isPopular: false },
      { name: "Filter Coffee", description: "Strong decoction coffee with frothy milk, served in a davara-tumbler", price: 25, category: "Beverages", image: img("filter-coffee.jpg"), isVeg: true, isPopular: false },
    ],
  },
  {
    mockId: "r-2",
    ownerMockId: "u-4",
    slug: "candyy-cafe",
    name: "Candyy Cafe",
    tagline: "Legendary since 1948 for its uniquely rich sambar",
    description:
      "Established in 1948, Candyy Cafe has been a Chennai institution for over seven decades. Famous for its deeply flavorful, one-of-a-kind sambar served alongside pillow-soft idlis and crisp dosas, it's a breakfast ritual for generations of Chennaiites.",
    coverImage: img("idli-coffee.jpg"),
    gallery: [img("dosa-chutneys.jpg"), img("thali-2.jpg"), img("vada-plate.jpg"), img("restaurant-table.jpg"), img("idli-banana-leaf.jpg"), img("filter-coffee.jpg")],
    cuisines: ["South Indian", "Tiffin", "Filter Coffee"],
    category: "Traditional Mess",
    priceRange: "₹",
    rating: 4.6,
    reviewCount: 845,
    location: { address: "236 Triplicane High Road, Triplicane", city: "Chennai", state: "Tamil Nadu", zip: "600005", lat: 13.0603, lng: 80.2762 },
    facilities: ["Filter Coffee", "Takeout", "Family Friendly", "Serving Since 1948"],
    openingHours: tiffinHours,
    isOpenNow: true,
    isFeatured: true,
    isTrending: false,
    isTopRated: true,
    seatsAvailable: 10,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: true,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Rava Idli", description: "Semolina steamed cakes studded with cashew and curry leaf", price: 50, category: "Tiffin", image: img("idli-coffee.jpg"), isVeg: true, isPopular: true },
      { name: "Ratna Special Sambar Idli", description: "Soft idlis soaked in the cafe's legendary rich sambar", price: 60, category: "Tiffin", image: img("sambar.jpg"), isVeg: true, isPopular: true },
      { name: "Masala Dosa", description: "Crisp dosa filled with spiced potato masala, tomato & coconut chutney", price: 90, category: "Tiffin", image: img("dosa-chutneys.jpg"), isVeg: true, isPopular: false },
      { name: "Ven Pongal", description: "Comforting rice and moong dal porridge tempered with pepper and cumin", price: 60, category: "Tiffin", image: img("thali-2.jpg"), isVeg: true, isPopular: false },
      { name: "Filter Coffee", description: "Strong decoction coffee with frothy milk", price: 25, category: "Beverages", image: img("filter-coffee.jpg"), isVeg: true, isPopular: false },
    ],
  },
  {
    mockId: "r-3",
    ownerMockId: "u-5",
    slug: "dindigul-thalappakatti",
    name: "Dindigul Thalappakatti",
    tagline: "World-famous Dindigul-style biryani since 1957",
    description:
      "Dindigul Thalappakatti brings its legendary Dindigul-style biryani — made with fragrant Seeraga Samba rice and a secret spice blend passed down through generations — to Coimbatore. A must-visit for biryani lovers across Tamil Nadu.",
    coverImage: img("biryani-2.jpg"),
    gallery: [img("biryani-2.jpg"), img("restaurant-table.jpg"), img("thali-1.jpg"), img("sambar.jpg"), img("filter-coffee.jpg"), img("dosa-tray.jpg")],
    cuisines: ["Biryani", "South Indian"],
    category: "Biryani Specialist",
    priceRange: "₹₹₹",
    rating: 4.8,
    reviewCount: 1240,
    location: { address: "100 Feet Road, Gandhipuram", city: "Coimbatore", state: "Tamil Nadu", zip: "641012", lat: 11.0177, lng: 76.9674 },
    facilities: ["Family Friendly", "Takeout", "Serving Since 1957", "Air Conditioned", "Parking Available"],
    openingHours: biryaniHours,
    isOpenNow: true,
    isFeatured: true,
    isTrending: true,
    isTopRated: true,
    seatsAvailable: 25,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: false,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Dindigul Mutton Biryani", description: "Seeraga samba rice slow-cooked with tender mutton and secret spice blend", price: 320, category: "Biryani", image: img("biryani-2.jpg"), isVeg: false, isPopular: true },
      { name: "Dindigul Chicken Biryani", description: "Signature short-grain biryani with bone-in chicken, served with brinjal chutney", price: 280, category: "Biryani", image: img("biryani-2.jpg"), isVeg: false, isPopular: true },
      { name: "Thalappakatti Chicken 65", description: "Deep-fried spiced chicken bites, a classic biryani side", price: 220, category: "Starters", image: img("restaurant-table.jpg"), isVeg: false, isPopular: false },
      { name: "Vegetable Biryani", description: "Seeraga samba rice layered with mixed vegetables and whole spices", price: 220, category: "Biryani", image: img("biryani-2.jpg"), isVeg: true, isPopular: true },
      { name: "Onion Raita", description: "Cooling yogurt with onion, served alongside biryani", price: 40, category: "Sides", image: img("thali-1.jpg"), isVeg: true, isPopular: false },
    ],
  },
  {
    mockId: "r-4",
    ownerMockId: "u-5",
    slug: "murugan-idli-shop",
    name: "Murugan Idli Shop",
    tagline: "Tamil Nadu's favourite idli, dosa & pongal chain",
    description:
      "A beloved chain revered for its consistent quality, Murugan Idli Shop serves feather-light idlis, crispy dosas, and comforting pongal made with traditional recipes. A reliable favorite for a quick, satisfying South Indian meal.",
    coverImage: img("murugan-idli-shop.png"),
    gallery: [img("murugan-idli-shop.png"), img("idli-banana-leaf.jpg"), img("idli-coffee.jpg"), img("dosa-3sauces.jpg"), img("vada-plate.jpg"), img("sambar.jpg")],
    cuisines: ["South Indian", "Tiffin", "Filter Coffee"],
    category: "Tiffin & Breakfast",
    priceRange: "₹",
    rating: 4.5,
    reviewCount: 980,
    location: { address: "17 DB Road, RS Puram", city: "Coimbatore", state: "Tamil Nadu", zip: "641002", lat: 11.006, lng: 76.9497 },
    facilities: ["Family Friendly", "Takeout", "Pure Vegetarian", "Air Conditioned"],
    openingHours: tiffinHours,
    isOpenNow: true,
    isFeatured: false,
    isTrending: true,
    isTopRated: true,
    seatsAvailable: 30,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: true,
    vegan: true,
    petFriendly: false,
    menu: [
      { name: "Idli (2 pcs)", description: "Soft steamed rice cakes with sambar and chutney", price: 40, category: "Tiffin", image: img("idli-banana-leaf.jpg"), isVeg: true, isPopular: true },
      { name: "Ghee Podi Idli", description: "Idli tossed in ghee and roasted lentil spice powder", price: 60, category: "Tiffin", image: img("idli-coffee.jpg"), isVeg: true, isPopular: true },
      { name: "Onion Rava Dosa", description: "Crisp semolina dosa loaded with onions, served with three chutneys", price: 90, category: "Tiffin", image: img("dosa-3sauces.jpg"), isVeg: true, isPopular: false },
      { name: "Ven Pongal", description: "Rice and moong dal porridge, tempered with ghee, pepper and cashew", price: 60, category: "Tiffin", image: img("thali-2.jpg"), isVeg: true, isPopular: false },
      { name: "Medu Vada", description: "Crispy lentil doughnuts served with sambar and coconut chutney", price: 45, category: "Tiffin", image: img("vada-plate.jpg"), isVeg: true, isPopular: false },
    ],
  },
  {
    mockId: "r-5",
    ownerMockId: "u-4",
    slug: "annalakshmi-restaurant",
    name: "Annalakshmi Restaurant",
    tagline: "Temple-inspired fine dining, purely vegetarian",
    description:
      "Annalakshmi offers a unique, temple-like fine-dining experience centered on authentic vegetarian cuisine. Run largely by volunteers who dedicate proceeds to charitable causes, every dish is prepared and served with a deep cultural and spiritual touch.",
    coverImage: img("thali-1.jpg"),
    gallery: [img("thali-1.jpg"), img("thali-2.jpg"), img("dosa-chutneys.jpg"), img("filter-coffee.jpg"), img("restaurant-table.jpg"), img("sambar.jpg")],
    cuisines: ["South Indian", "North Indian", "Vegetarian"],
    category: "Fine Dining",
    priceRange: "₹₹₹₹",
    rating: 4.9,
    reviewCount: 530,
    location: { address: "Karpagambal Nagar, Anna Salai", city: "Chennai", state: "Tamil Nadu", zip: "600002", lat: 13.0645, lng: 80.2707 },
    facilities: ["Cultural Ambience", "Live Classical Music", "Pure Vegetarian", "Charitable Trust", "Private Dining"],
    openingHours: fineDiningHours,
    isOpenNow: true,
    isFeatured: true,
    isTrending: false,
    isTopRated: true,
    seatsAvailable: 6,
    outdoorSeating: false,
    liveMusic: true,
    vegetarian: true,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Annalakshmi Thali", description: "An elaborate vegetarian feast of rice, curries, kootu, poriyal and payasam", price: 450, category: "Thali", image: img("thali-1.jpg"), isVeg: true, isPopular: true },
      { name: "Bisi Bele Bath", description: "Spiced rice and lentil dish simmered with vegetables and tamarind", price: 220, category: "Mains", image: img("thali-2.jpg"), isVeg: true, isPopular: false },
      { name: "Kootu Curry", description: "Vegetables and lentils simmered in a mild coconut gravy", price: 180, category: "Mains", image: img("sambar.jpg"), isVeg: true, isPopular: false },
      { name: "Semiya Payasam", description: "Warm vermicelli pudding simmered in milk, cardamom and cashews", price: 120, category: "Desserts", image: img("restaurant-table.jpg"), isVeg: true, isPopular: false },
    ],
  },
  {
    mockId: "r-6",
    ownerMockId: "u-5",
    slug: "karpagambal-mess",
    name: "Karpagambal Mess",
    tagline: "Traditional Mylapore mess famous for Keerai Vada",
    description:
      "A cherished neighborhood institution in Mylapore, Karpagambal Mess is known for its warm, old-school atmosphere and authentic local snacks — especially the famous Keerai Vada, a crispy spinach-studded lentil fritter found nowhere else quite like this.",
    coverImage: img("vada-plate.jpg"),
    gallery: [img("vada-plate.jpg"), img("dosa-tray.jpg"), img("idli-coffee.jpg"), img("sambar.jpg"), img("thali-2.jpg"), img("restaurant-table.jpg")],
    cuisines: ["South Indian", "Tiffin", "Filter Coffee"],
    category: "Traditional Mess",
    priceRange: "₹₹₹₹",
    rating: 4.6,
    reviewCount: 398,
    location: { address: "12 South Mada Street, Mylapore", city: "Chennai", state: "Tamil Nadu", zip: "600004", lat: 13.033, lng: 80.261 },
    facilities: ["Traditional Seating", "Filter Coffee", "Family Run Since Decades", "Takeout"],
    openingHours: tiffinHours,
    isOpenNow: true,
    isFeatured: false,
    isTrending: false,
    isTopRated: true,
    seatsAvailable: 12,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: true,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Keerai Vada", description: "The mess's famous spinach-studded lentil fritter", price: 40, category: "Tiffin", image: img("vada-plate.jpg"), isVeg: true, isPopular: true },
      { name: "Idli Sambar", description: "Steamed idlis served with a generous ladle of piping hot sambar", price: 45, category: "Tiffin", image: img("idli-coffee.jpg"), isVeg: true, isPopular: true },
      { name: "Set Dosa", description: "Soft, spongy mini dosas served in a stack of three", price: 70, category: "Tiffin", image: img("dosa-tray.jpg"), isVeg: true, isPopular: false },
      { name: "Filter Coffee", description: "Strong decoction coffee with frothy milk", price: 25, category: "Beverages", image: img("filter-coffee.jpg"), isVeg: true, isPopular: false },
    ],
  },
  {
    mockId: "r-7",
    ownerMockId: "u-4",
    slug: "park-elanza",
    name: "Park Elanza",
    tagline: "Upscale multi-cuisine dining in the heart of Coimbatore",
    description:
      "Park Elanza brings together a refined ambience and a menu spanning South Indian, North Indian, and continental favorites. A popular choice for family celebrations and business dinners alike, with attentive service and a polished dining room.",
    coverImage: img("park-elanza.jpg"),
    gallery: [img("park-elanza.jpg"), img("thali-2.jpg"), img("restaurant-table.jpg"), img("biryani-2.jpg"), img("filter-coffee.jpg"), img("thali-1.jpg")],
    cuisines: ["South Indian", "North Indian"],
    category: "Fine Dining",
    priceRange: "₹₹₹",
    rating: 4.5,
    reviewCount: 276,
    location: { address: "Race Course Road", city: "Coimbatore", state: "Tamil Nadu", zip: "641018", lat: 11.0053, lng: 76.9611 },
    facilities: ["Family Friendly", "Air Conditioned", "Parking Available", "Private Dining"],
    openingHours: fineDiningHours,
    isOpenNow: true,
    isFeatured: false,
    isTrending: false,
    isTopRated: false,
    seatsAvailable: 18,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: false,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Paneer Butter Masala", description: "Cottage cheese cubes simmered in a rich buttery tomato gravy", price: 260, category: "Mains", image: img("thali-2.jpg"), isVeg: true, isPopular: true },
      { name: "Chettinad Chicken Curry", description: "Fiery Chettinad-spiced chicken curry with roasted spices", price: 320, category: "Mains", image: img("biryani-2.jpg"), isVeg: false, isPopular: true },
      { name: "Elanza Mixed Grill Platter", description: "Chef's selection of grilled kebabs and tandoori bites", price: 450, category: "Starters", image: img("restaurant-table.jpg"), isVeg: false, isPopular: false },
      { name: "South Indian Filter Coffee", description: "Strong decoction coffee with frothy milk", price: 60, category: "Beverages", image: img("filter-coffee.jpg"), isVeg: true, isPopular: false },
    ],
  },
  {
    mockId: "r-8",
    ownerMockId: "u-4",
    slug: "the-french-door",
    name: "The French Door",
    tagline: "European & French-inspired bistro dining in R.S. Puram",
    description:
      "A charming bistro bringing French and wider European classics to Coimbatore — think onion soup, perfectly grilled fish, and a wine list to match. Intimate seating and warm service make it a favourite for date nights and quiet celebrations.",
    coverImage: img("the-french-door.png"),
    gallery: [img("the-french-door.png"), img("restaurant-table.jpg"), img("thali-2.jpg"), img("filter-coffee.jpg"), img("dosa-tray.jpg"), img("thali-1.jpg")],
    cuisines: ["European"],
    category: "Fine Dining",
    priceRange: "₹₹₹₹",
    rating: 4.6,
    reviewCount: 312,
    location: { address: "D.B. Road, R.S. Puram", city: "Coimbatore", state: "Tamil Nadu", zip: "641002", lat: 11.0053, lng: 76.9515 },
    facilities: ["Air Conditioned", "Private Dining", "Parking Available", "Wine List"],
    openingHours: fineDiningHours,
    isOpenNow: true,
    isFeatured: true,
    isTrending: true,
    isTopRated: false,
    seatsAvailable: 14,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: false,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "French Onion Soup", description: "Caramelized onion soup, gruyère crouton", price: 320, category: "Starters", image: img("restaurant-table.jpg"), isVeg: true, isPopular: true },
      { name: "Pan-Seared Fish", description: "Catch of the day with lemon butter sauce and seasonal vegetables", price: 620, category: "Mains", image: img("thali-2.jpg"), isVeg: false, isPopular: true },
      { name: "Ratatouille", description: "Slow-cooked Provençal vegetable stew", price: 380, category: "Mains", image: img("thali-1.jpg"), isVeg: true, isPopular: false },
      { name: "Crème Brûlée", description: "Classic vanilla custard with a caramelized sugar crust", price: 260, category: "Desserts", image: img("filter-coffee.jpg"), isVeg: true, isPopular: true },
    ],
  },
  {
    mockId: "r-9",
    ownerMockId: "u-5",
    slug: "the-pavilion",
    name: "The Pavilion",
    tagline: "Upscale multi-cuisine dining at The Residency Towers",
    description:
      "Set inside The Residency Towers, The Pavilion serves a polished multi-cuisine spread spanning Continental, North Indian, and South Indian favourites. A dependable choice for business dinners and family celebrations alike.",
    coverImage: img("the-pavilion.png"),
    gallery: [img("the-pavilion.png"), img("thali-2.jpg"), img("restaurant-table.jpg"), img("biryani-2.jpg"), img("dosa-chutneys.jpg"), img("filter-coffee.jpg")],
    cuisines: ["North Indian", "European", "South Indian"],
    category: "Fine Dining",
    priceRange: "₹₹₹₹",
    rating: 4.5,
    reviewCount: 268,
    location: { address: "Avinashi Road", city: "Coimbatore", state: "Tamil Nadu", zip: "641018", lat: 11.0186, lng: 76.9697 },
    facilities: ["Air Conditioned", "Parking Available", "Family Friendly", "Private Dining"],
    openingHours: fineDiningHours,
    isOpenNow: true,
    isFeatured: false,
    isTrending: false,
    isTopRated: false,
    seatsAvailable: 20,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: false,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Continental Grilled Platter", description: "Chef's selection of grilled meats and vegetables", price: 650, category: "Mains", image: img("restaurant-table.jpg"), isVeg: false, isPopular: true },
      { name: "Butter Chicken", description: "Tandoori chicken simmered in a creamy tomato gravy", price: 420, category: "Mains", image: img("biryani-2.jpg"), isVeg: false, isPopular: true },
      { name: "Paneer Tikka", description: "Char-grilled cottage cheese marinated in spiced yogurt", price: 340, category: "Starters", image: img("thali-2.jpg"), isVeg: true, isPopular: false },
      { name: "Dosa Trio", description: "Three South Indian dosa varieties with chutneys", price: 280, category: "Tiffin", image: img("dosa-chutneys.jpg"), isVeg: true, isPopular: false },
    ],
  },
  {
    mockId: "r-10",
    ownerMockId: "u-4",
    slug: "bird-on-tree",
    name: "Bird on Tree",
    tagline: "Fine dining featuring global, Pan-Asian & Indian cuisine",
    description:
      "Bird on Tree pairs a striking, plant-filled dining room on Race Course with a menu that hops confidently between Pan-Asian small plates, global favourites, and Indian classics — a go-to for a memorable evening out in Coimbatore.",
    coverImage: img("bird-on-tree.png"),
    gallery: [img("bird-on-tree.png"), img("dosa-3sauces.jpg"), img("restaurant-table.jpg"), img("biryani-2.jpg"), img("thali-2.jpg"), img("filter-coffee.jpg")],
    cuisines: ["Pan-Asian", "North Indian"],
    category: "Fine Dining",
    priceRange: "₹₹₹₹",
    rating: 4.7,
    reviewCount: 421,
    location: { address: "Race Course Road", city: "Coimbatore", state: "Tamil Nadu", zip: "641018", lat: 11.0046, lng: 76.9622 },
    facilities: ["Air Conditioned", "Outdoor Seating", "Parking Available", "Instagrammable Decor"],
    openingHours: fineDiningHours,
    isOpenNow: true,
    isFeatured: true,
    isTrending: true,
    isTopRated: true,
    seatsAvailable: 22,
    outdoorSeating: true,
    liveMusic: false,
    vegetarian: false,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Dim Sum Basket", description: "Steamed Pan-Asian dumplings, assorted fillings", price: 420, category: "Starters", image: img("dosa-3sauces.jpg"), isVeg: false, isPopular: true },
      { name: "Pad Thai", description: "Stir-fried rice noodles, tofu or chicken, tamarind sauce", price: 480, category: "Mains", image: img("restaurant-table.jpg"), isVeg: false, isPopular: true },
      { name: "Butter Garlic Prawns", description: "Wok-tossed prawns in a butter garlic glaze", price: 590, category: "Mains", image: img("biryani-2.jpg"), isVeg: false, isPopular: false },
      { name: "Chilli Paneer", description: "Indo-Chinese battered cottage cheese in a spicy glaze", price: 360, category: "Starters", image: img("thali-2.jpg"), isVeg: true, isPopular: false },
    ],
  },
  {
    mockId: "r-11",
    ownerMockId: "u-5",
    slug: "sree-annapoorna",
    name: "Sree Annapoorna",
    tagline: "Legendary vegetarian South Indian breakfast & filter coffee",
    description:
      "A Coimbatore institution, Sree Annapoorna has been serving impeccable vegetarian tiffin — soft idlis, crisp dosas, and rich filter coffee — for decades. Consistently packed, and consistently excellent.",
    coverImage: img("sree-annapoorna.png"),
    gallery: [img("sree-annapoorna.png"), img("idli-coffee.jpg"), img("idli-banana-leaf.jpg"), img("dosa-tray.jpg"), img("vada-plate.jpg"), img("filter-coffee.jpg")],
    cuisines: ["South Indian", "Tiffin", "Filter Coffee", "Vegetarian"],
    category: "Tiffin & Breakfast",
    priceRange: "₹₹",
    rating: 4.6,
    reviewCount: 890,
    location: { address: "D.B. Road, R.S. Puram", city: "Coimbatore", state: "Tamil Nadu", zip: "641002", lat: 11.0064, lng: 76.9498 },
    facilities: ["Family Friendly", "Takeout", "Pure Vegetarian", "Air Conditioned"],
    openingHours: tiffinHours,
    isOpenNow: true,
    isFeatured: false,
    isTrending: true,
    isTopRated: true,
    seatsAvailable: 40,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: true,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Idli", description: "Soft steamed rice cakes with sambar and coconut chutney", price: 45, category: "Tiffin", image: img("idli-coffee.jpg"), isVeg: true, isPopular: true },
      { name: "Ghee Roast Dosa", description: "Crisp rice crepe roasted in ghee", price: 85, category: "Tiffin", image: img("dosa-tray.jpg"), isVeg: true, isPopular: true },
      { name: "Medu Vada", description: "Crispy lentil doughnuts with sambar and chutney", price: 50, category: "Tiffin", image: img("vada-plate.jpg"), isVeg: true, isPopular: false },
      { name: "Filter Coffee", description: "Strong decoction coffee with frothy milk", price: 30, category: "Beverages", image: img("filter-coffee.jpg"), isVeg: true, isPopular: true },
    ],
  },
  {
    mockId: "r-12",
    ownerMockId: "u-4",
    slug: "haribhavanam",
    name: "Haribhavanam",
    tagline: "Famous regional non-vegetarian Kongu & Chettinad cuisine",
    description:
      "Haribhavanam specializes in the bold, robustly spiced Kongu Nadu and Chettinad meat dishes Coimbatore is known for — country chicken curry, mutton chukka, and more, best mopped up with a hot parotta.",
    coverImage: img("haribhavanam.png"),
    gallery: [img("haribhavanam.png"), img("biryani-2.jpg"), img("restaurant-table.jpg"), img("thali-1.jpg"), img("sambar.jpg"), img("dosa-tray.jpg")],
    cuisines: ["Chettinad", "South Indian"],
    category: "Non-Veg Specialist",
    priceRange: "₹₹₹",
    rating: 4.5,
    reviewCount: 456,
    location: { address: "Sivananda Colony", city: "Coimbatore", state: "Tamil Nadu", zip: "641012", lat: 11.0126, lng: 76.9764 },
    facilities: ["Family Friendly", "Takeout", "Air Conditioned", "Parking Available"],
    openingHours: biryaniHours,
    isOpenNow: true,
    isFeatured: false,
    isTrending: false,
    isTopRated: true,
    seatsAvailable: 24,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: false,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Naatu Kozhi Curry", description: "Country chicken slow-cooked in Kongu-style spices", price: 380, category: "Mains", image: img("biryani-2.jpg"), isVeg: false, isPopular: true },
      { name: "Mutton Chukka", description: "Dry-roasted mutton tossed with roasted spices and curry leaf", price: 420, category: "Mains", image: img("restaurant-table.jpg"), isVeg: false, isPopular: true },
      { name: "Parotta", description: "Layered flatbread, served flaky and hot", price: 30, category: "Breads", image: img("thali-1.jpg"), isVeg: true, isPopular: true },
      { name: "Fish Fry", description: "Pan-fried fish marinated in Kongu spice blend", price: 340, category: "Starters", image: img("sambar.jpg"), isVeg: false, isPopular: false },
    ],
  },
  {
    mockId: "r-13",
    ownerMockId: "u-5",
    slug: "shree-anandhaas",
    name: "Shree Anandhaas",
    tagline: "Popular South & North Indian vegetarian fare",
    description:
      "A firm local favourite, Shree Anandhaas serves a broad, reliable spread of South and North Indian vegetarian dishes — from tiffin at breakfast to full thalis at dinner — in a bright, family-friendly setting.",
    coverImage: img("shree-anandhaas.png"),
    gallery: [img("shree-anandhaas.png"), img("thali-1.jpg"), img("dosa-chutneys.jpg"), img("idli-banana-leaf.jpg"), img("thali-2.jpg"), img("filter-coffee.jpg")],
    cuisines: ["South Indian", "North Indian", "Vegetarian"],
    category: "Vegetarian Restaurant",
    priceRange: "₹₹",
    rating: 4.4,
    reviewCount: 512,
    location: { address: "Avinashi Road", city: "Coimbatore", state: "Tamil Nadu", zip: "641018", lat: 11.0166, lng: 76.9682 },
    facilities: ["Family Friendly", "Takeout", "Pure Vegetarian", "Air Conditioned"],
    openingHours: biryaniHours,
    isOpenNow: true,
    isFeatured: false,
    isTrending: false,
    isTopRated: false,
    seatsAvailable: 35,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: true,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Anandhaas Thali", description: "Full vegetarian thali with seasonal curries and sweet", price: 260, category: "Thali", image: img("thali-1.jpg"), isVeg: true, isPopular: true },
      { name: "Paneer Butter Masala", description: "Cottage cheese cubes in a rich buttery tomato gravy", price: 260, category: "Mains", image: img("thali-2.jpg"), isVeg: true, isPopular: true },
      { name: "Masala Dosa", description: "Crisp dosa filled with spiced potato masala", price: 100, category: "Tiffin", image: img("dosa-chutneys.jpg"), isVeg: true, isPopular: false },
      { name: "Gulab Jamun", description: "Warm milk-solid dumplings soaked in rose syrup", price: 80, category: "Desserts", image: img("idli-banana-leaf.jpg"), isVeg: true, isPopular: false },
    ],
  },
  {
    mockId: "r-14",
    ownerMockId: "u-4",
    slug: "junior-kuppanna",
    name: "Junior Kuppanna",
    tagline: "Classic non-vegetarian dining specializing in regional meat dishes",
    description:
      "Junior Kuppanna is the address for serious Kongu-style non-vegetarian food — naatu kozhi (country chicken) curry, mutton chukka, and crisp parottas, served in generous, no-nonsense portions.",
    coverImage: img("restaurant-table.jpg"),
    gallery: [img("restaurant-table.jpg"), img("biryani-2.jpg"), img("thali-2.jpg"), img("sambar.jpg"), img("dosa-tray.jpg"), img("thali-1.jpg")],
    cuisines: ["Chettinad", "South Indian"],
    category: "Non-Veg Specialist",
    priceRange: "₹₹₹",
    rating: 4.6,
    reviewCount: 634,
    location: { address: "Trichy Road", city: "Coimbatore", state: "Tamil Nadu", zip: "641018", lat: 10.9938, lng: 76.9853 },
    facilities: ["Family Friendly", "Takeout", "Parking Available", "Air Conditioned"],
    openingHours: biryaniHours,
    isOpenNow: true,
    isFeatured: false,
    isTrending: true,
    isTopRated: true,
    seatsAvailable: 28,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: false,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Naatu Kozhi Curry", description: "Signature country chicken curry, Kongu-style", price: 400, category: "Mains", image: img("biryani-2.jpg"), isVeg: false, isPopular: true },
      { name: "Mutton Chukka", description: "Dry-roasted mutton with roasted spice coating", price: 450, category: "Mains", image: img("restaurant-table.jpg"), isVeg: false, isPopular: true },
      { name: "Chicken 65", description: "Deep-fried spiced chicken bites", price: 280, category: "Starters", image: img("thali-2.jpg"), isVeg: false, isPopular: true },
      { name: "Parotta (2 pcs)", description: "Flaky layered flatbread", price: 35, category: "Breads", image: img("thali-1.jpg"), isVeg: true, isPopular: false },
    ],
  },
  {
    mockId: "r-15",
    ownerMockId: "u-5",
    slug: "avartana",
    name: "Avartana",
    tagline: "Progressive South Indian tasting menus at ITC Grand Chola",
    description:
      "Avartana reimagines South Indian cuisine as a multi-course tasting journey — inventive plating, regional ingredients, and a dramatic showpiece dessert course, set within the grandeur of ITC Grand Chola.",
    coverImage: img("avartana.png"),
    gallery: [img("avartana.png"), img("thali-2.jpg"), img("thali-1.jpg"), img("sambar.jpg"), img("filter-coffee.jpg"), img("restaurant-table.jpg")],
    cuisines: ["South Indian"],
    category: "Fine Dining",
    priceRange: "₹₹₹₹",
    rating: 4.8,
    reviewCount: 587,
    location: { address: "63, Mount Road, Guindy", city: "Chennai", state: "Tamil Nadu", zip: "600032", lat: 13.0104, lng: 80.2177 },
    facilities: ["Air Conditioned", "Valet Parking", "Private Dining", "Tasting Menu Only"],
    openingHours: fineDiningHours,
    isOpenNow: true,
    isFeatured: true,
    isTrending: true,
    isTopRated: true,
    seatsAvailable: 16,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: false,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Idiyappam & Curry Course", description: "String hoppers with a trio of regional curries, tasting-menu style", price: 950, category: "Tasting Menu", image: img("thali-2.jpg"), isVeg: true, isPopular: true },
      { name: "Chettinad Course", description: "Progressive plating of Chettinad spices and technique", price: 1100, category: "Tasting Menu", image: img("sambar.jpg"), isVeg: false, isPopular: true },
      { name: "Payasam Reimagined", description: "Deconstructed semiya payasam, tasting-menu dessert course", price: 480, category: "Desserts", image: img("filter-coffee.jpg"), isVeg: true, isPopular: false },
    ],
  },
  {
    mockId: "r-16",
    ownerMockId: "u-4",
    slug: "southern-spice",
    name: "Southern Spice",
    tagline: "Authentic classical South Indian cuisine at Taj Coromandel",
    description:
      "Southern Spice serves classical South Indian cuisine across all four southern states, from Chettinad curries to Kerala seafood, in an elegant dining room at the Taj Coromandel — a Chennai fine-dining landmark.",
    coverImage: img("southern-spice.png"),
    gallery: [img("southern-spice.png"), img("sambar.jpg"), img("thali-1.jpg"), img("biryani-2.jpg"), img("dosa-tray.jpg"), img("filter-coffee.jpg")],
    cuisines: ["South Indian", "Chettinad"],
    category: "Fine Dining",
    priceRange: "₹₹₹₹",
    rating: 4.7,
    reviewCount: 703,
    location: { address: "37 Mahatma Gandhi Road, Nungambakkam", city: "Chennai", state: "Tamil Nadu", zip: "600034", lat: 13.0569, lng: 80.2496 },
    facilities: ["Air Conditioned", "Valet Parking", "Private Dining", "Award Winning"],
    openingHours: fineDiningHours,
    isOpenNow: true,
    isFeatured: true,
    isTrending: false,
    isTopRated: true,
    seatsAvailable: 20,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: false,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Chettinad Crab Curry", description: "Crab simmered in a fiery Chettinad masala", price: 890, category: "Mains", image: img("sambar.jpg"), isVeg: false, isPopular: true },
      { name: "Malabar Fish Biryani", description: "Kerala-style layered fish biryani", price: 720, category: "Biryani", image: img("biryani-2.jpg"), isVeg: false, isPopular: true },
      { name: "Appam & Stew", description: "Lacy rice pancakes with a mild coconut vegetable stew", price: 480, category: "Mains", image: img("thali-1.jpg"), isVeg: true, isPopular: false },
      { name: "Filter Coffee", description: "Strong decoction coffee with frothy milk", price: 90, category: "Beverages", image: img("filter-coffee.jpg"), isVeg: true, isPopular: false },
    ],
  },
  {
    mockId: "r-17",
    ownerMockId: "u-5",
    slug: "jamavar",
    name: "Jamavar",
    tagline: "Royal North Indian dining at The Leela Palace",
    description:
      "Jamavar brings royal North Indian cuisine to The Leela Palace — melt-in-the-mouth kebabs, slow-cooked dals, and biryanis rooted in Mughlai and Awadhi traditions, served with palace-worthy hospitality.",
    coverImage: img("jamavar.png"),
    gallery: [img("jamavar.png"), img("biryani-2.jpg"), img("thali-2.jpg"), img("restaurant-table.jpg"), img("thali-1.jpg"), img("filter-coffee.jpg")],
    cuisines: ["North Indian"],
    category: "Fine Dining",
    priceRange: "₹₹₹₹",
    rating: 4.8,
    reviewCount: 449,
    location: { address: "MRC Nagar, Adyar", city: "Chennai", state: "Tamil Nadu", zip: "600028", lat: 13.0195, lng: 80.2717 },
    facilities: ["Air Conditioned", "Valet Parking", "Private Dining", "Live Kitchen Counter"],
    openingHours: fineDiningHours,
    isOpenNow: true,
    isFeatured: true,
    isTrending: false,
    isTopRated: true,
    seatsAvailable: 18,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: false,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Galouti Kebab", description: "Melt-in-the-mouth minced lamb kebab, Awadhi style", price: 780, category: "Starters", image: img("biryani-2.jpg"), isVeg: false, isPopular: true },
      { name: "Dal Jamavar", description: "Slow-cooked black lentils, finished with cream", price: 480, category: "Mains", image: img("thali-2.jpg"), isVeg: true, isPopular: true },
      { name: "Lucknowi Biryani", description: "Fragrant dum-cooked biryani, Awadhi tradition", price: 850, category: "Biryani", image: img("biryani-2.jpg"), isVeg: false, isPopular: true },
      { name: "Sheermal", description: "Saffron-scented mildly sweet flatbread", price: 120, category: "Breads", image: img("thali-1.jpg"), isVeg: true, isPopular: false },
    ],
  },
  {
    mockId: "r-18",
    ownerMockId: "u-4",
    slug: "ratna-cafe",
    name: "Ratna Cafe",
    tagline: "Legendary ghee-laden sambar idli since 1948",
    description:
      "A Triplicane institution with a vintage 1940s cafe feel, Ratna Cafe is famous for idlis submerged in generous ghee-laced sambar, served on steel plates alongside strong filter coffee in a davara-tumbler. A nostalgic taste of old Chennai.",
    coverImage: img("ratna-cafe.png"),
    gallery: [img("ratna-cafe.png"), img("idli-coffee.jpg"), img("sambar.jpg"), img("dosa-tray.jpg"), img("vada-plate.jpg"), img("filter-coffee.jpg")],
    cuisines: ["South Indian", "Tiffin", "Filter Coffee"],
    category: "Traditional Mess",
    priceRange: "₹",
    rating: 4.5,
    reviewCount: 620,
    location: { address: "295 Triplicane High Road, Triplicane", city: "Chennai", state: "Tamil Nadu", zip: "600005", lat: 13.0604, lng: 80.2793 },
    facilities: ["Family Friendly", "Takeout", "Serving Since 1948"],
    openingHours: tiffinHours,
    isOpenNow: true,
    isFeatured: false,
    isTrending: true,
    isTopRated: true,
    seatsAvailable: 26,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: true,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Sambar Idli", description: "Soft idlis submerged in generous ghee-laced sambar", price: 60, category: "Tiffin", image: img("ratna-cafe.png"), isVeg: true, isPopular: true },
      { name: "Ghee Roast Dosa", description: "Crisp rice crepe roasted in ghee", price: 90, category: "Tiffin", image: img("dosa-tray.jpg"), isVeg: true, isPopular: true },
      { name: "Medu Vada", description: "Crispy lentil doughnuts with sambar and chutney", price: 55, category: "Tiffin", image: img("vada-plate.jpg"), isVeg: true, isPopular: false },
      { name: "Filter Coffee", description: "Strong decoction coffee served in a davara-tumbler", price: 35, category: "Beverages", image: img("filter-coffee.jpg"), isVeg: true, isPopular: true },
    ],
  },
  {
    mockId: "r-19",
    ownerMockId: "u-5",
    slug: "buhari",
    name: "Buhari",
    tagline: "Birthplace of the original Chicken 65, since 1951",
    description:
      "Buhari is the Chennai institution credited with inventing Chicken 65 — fiery, crisp fried chicken tossed with curry leaves and green chillies. A retro 1950s dining room and a menu of Chennai-style biryanis keep generations coming back.",
    coverImage: img("buhari.png"),
    gallery: [img("buhari.png"), img("biryani-2.jpg"), img("restaurant-table.jpg"), img("thali-1.jpg"), img("thali-2.jpg"), img("sambar.jpg")],
    cuisines: ["Biryani", "South Indian"],
    category: "Non-Veg Specialist",
    priceRange: "₹₹",
    rating: 4.4,
    reviewCount: 540,
    location: { address: "Grand Ambassador Building, Wallajah Road, Anna Salai", city: "Chennai", state: "Tamil Nadu", zip: "600002", lat: 13.0604, lng: 80.2707 },
    facilities: ["Family Friendly", "Takeout", "Air Conditioned", "Serving Since 1951"],
    openingHours: biryaniHours,
    isOpenNow: true,
    isFeatured: false,
    isTrending: true,
    isTopRated: true,
    seatsAvailable: 32,
    outdoorSeating: false,
    liveMusic: false,
    vegetarian: false,
    vegan: false,
    petFriendly: false,
    menu: [
      { name: "Original Chicken 65", description: "The dish that started it all — fiery crisp fried chicken with curry leaves", price: 320, category: "Starters", image: img("buhari.png"), isVeg: false, isPopular: true },
      { name: "Chennai Chicken Biryani", description: "Short-grain biryani rice, Chennai-style masala", price: 260, category: "Biryani", image: img("biryani-2.jpg"), isVeg: false, isPopular: true },
      { name: "Mutton Kheema", description: "Slow-cooked minced mutton in a rich onion-tomato masala", price: 340, category: "Mains", image: img("restaurant-table.jpg"), isVeg: false, isPopular: false },
      { name: "Parotta", description: "Layered flatbread, served flaky and hot", price: 30, category: "Breads", image: img("thali-1.jpg"), isVeg: true, isPopular: true },
    ],
  },
];

export const seedReservations = [
  { restaurantMockId: "r-1", userMockId: "u-1", date: "2026-07-20", time: "7:30 AM", guests: 2, specialRequest: "Window seat if possible, celebrating anniversary.", status: "upcoming", createdAt: "2026-07-10" },
  { restaurantMockId: "r-2", userMockId: "u-1", date: "2026-07-25", time: "8:00 AM", guests: 4, status: "upcoming", createdAt: "2026-07-12" },
  { restaurantMockId: "r-3", userMockId: "u-1", date: "2026-05-14", time: "1:00 PM", guests: 3, status: "completed", createdAt: "2026-05-01" },
  { restaurantMockId: "r-6", userMockId: "u-1", date: "2026-04-02", time: "8:30 AM", guests: 2, status: "cancelled", createdAt: "2026-03-20" },
  { restaurantMockId: "r-5", userMockId: "u-2", date: "2026-07-18", time: "7:00 PM", guests: 5, specialRequest: "One guest has a nut allergy.", status: "upcoming", createdAt: "2026-07-08" },
  { restaurantMockId: "r-4", userMockId: "u-2", date: "2026-07-22", time: "9:00 AM", guests: 3, status: "upcoming", createdAt: "2026-07-11" },
];

export const seedReviews = [
  { restaurantMockId: "r-1", userMockId: "u-1", rating: 5, title: "Best idli-sambar in Mylapore", comment: "Arrived at 7 AM and there was already a queue out the door — for good reason. The idlis are impossibly soft and that chutney has serious heat. Worth every minute of the wait.", createdAt: "2025-06-02", ownerReply: { message: "Thank you! We're glad you braved the morning queue — see you again soon.", createdAt: "2025-06-03" }, helpfulCount: 34 },
  { restaurantMockId: "r-1", userMockId: "u-2", rating: 4, title: "Authentic but no-frills", comment: "Don't expect fancy seating — this is a proper mess. But the sambar vada alone makes it worth a visit. Cash only, so come prepared.", createdAt: "2025-05-18", helpfulCount: 14 },
  { restaurantMockId: "r-2", userMockId: "u-3", rating: 5, title: "That sambar is legendary for a reason", comment: "Been coming here since I was a kid — the sambar recipe genuinely hasn't changed and it's still the best in Chennai. Order the sambar idli, thank me later.", createdAt: "2025-06-10", ownerReply: { message: "So happy to hear you keep coming back! Since 1948, some things just shouldn't change.", createdAt: "2025-06-11" }, helpfulCount: 41 },
  { restaurantMockId: "r-2", userMockId: "u-1", rating: 4, title: "Busy but worth it", comment: "Gets packed on weekend mornings, but the masala dosa is crisp and generously filled. Great filter coffee too.", createdAt: "2025-04-27", helpfulCount: 19 },
  { restaurantMockId: "r-3", userMockId: "u-2", rating: 5, title: "Worth the hype — genuinely the best biryani", comment: "The Seeraga Samba rice makes such a difference — every grain is fragrant and separate. The mutton biryani is rich without being heavy. Best in Coimbatore, hands down.", createdAt: "2025-05-30", ownerReply: { message: "Thank you for the kind words! Our spice blend recipe has been in the family since 1957.", createdAt: "2025-05-31" }, helpfulCount: 52 },
  { restaurantMockId: "r-3", userMockId: "u-3", rating: 5, title: "Even the vegetable biryani is outstanding", comment: "I don't eat meat and was still blown away — the vegetable biryani has just as much depth of flavor. The onion raita is the perfect cooling side.", createdAt: "2025-06-15", helpfulCount: 22 },
  { restaurantMockId: "r-4", userMockId: "u-1", rating: 5, title: "Consistently excellent, every single time", comment: "What I love most is how reliable it is — the idli and ghee podi combo never disappoints. Clean, fast service too.", createdAt: "2025-06-20", helpfulCount: 21 },
  { restaurantMockId: "r-4", userMockId: "u-2", rating: 4, title: "Great for a quick, satisfying meal", comment: "The onion rava dosa is fantastic and the pongal is proper comfort food. Gets crowded during breakfast hours.", createdAt: "2025-03-11", ownerReply: { message: "Thanks so much for visiting! We're glad the rava dosa hit the spot.", createdAt: "2025-03-12" }, helpfulCount: 27 },
  { restaurantMockId: "r-5", userMockId: "u-3", rating: 5, title: "A truly unique dining experience", comment: "The temple-inspired ambience and the live veena music make this feel like a cultural event, not just a meal. The full thali is an incredible spread and it all goes to charity — what's not to love.", createdAt: "2025-06-05", helpfulCount: 29 },
  { restaurantMockId: "r-5", userMockId: "u-1", rating: 5, title: "Special occasion worthy", comment: "Took my parents here for their anniversary and it exceeded expectations. Elegant, thoughtful, and the payasam was a beautiful finish.", createdAt: "2025-04-12", helpfulCount: 17 },
  { restaurantMockId: "r-6", userMockId: "u-2", rating: 5, title: "Keerai Vada is a revelation", comment: "Never had anything like it — crispy on the outside, packed with greens inside. This mess has serious old-school charm.", createdAt: "2025-06-01", helpfulCount: 18 },
  { restaurantMockId: "r-6", userMockId: "u-3", rating: 4, title: "Neighborhood gem", comment: "Simple, unpretentious, and delicious. The set dosa is soft and the filter coffee is the perfect way to end breakfast.", createdAt: "2025-05-08", helpfulCount: 12 },
];

export const seedNotifications = [
  { userMockId: "u-1", title: "Reservation Confirmed", message: "Your table for 2 at Rayar's Mess on Jul 20, 7:30 AM is confirmed.", type: "reservation", isRead: false, createdAt: "2026-07-10T10:00:00" },
  { userMockId: "u-1", title: "Owner replied to your review", message: "Rayar's Mess replied to your review: \"Thank you! We're glad you braved the morning queue...\"", type: "review", isRead: false, createdAt: "2026-07-11T09:15:00" },
  { userMockId: "u-1", title: "20% off this weekend", message: "Enjoy 20% off at participating restaurants this Saturday & Sunday.", type: "promo", isRead: true, createdAt: "2026-07-08T08:00:00" },
  { userMockId: "u-1", title: "Reminder: upcoming reservation", message: "Don't forget your reservation at Candyy Cafe tomorrow at 8:00 AM.", type: "reservation", isRead: true, createdAt: "2026-07-24T18:00:00" },
  { userMockId: "u-1", title: "Welcome to BookMyBite!", message: "Thanks for joining — start exploring restaurants near you.", type: "system", isRead: true, createdAt: "2023-08-14T12:00:00" },
];
